#!/bin/bash

# start_api is for users to launch the application
# stack into their account using the release
# package from GitHub

while getopts "b:t:" arg; do
	case $arg in
		b) ARTIFACT_BUCKET=$OPTARG;;
		t) TABLE_NAME=$OPTARG;;
		*) echo "flag not supported"; exit 1;;
	esac
done

ID=$(uuidgen)
ID=${ID,,}

REGION=$( aws configure get region )

if [ -z $ARTIFACT_BUCKET ]
then
	ARTIFACT_BUCKET=todalytics-artifact-$ID
	aws s3api create-bucket --bucket $ARTIFACT_BUCKET --region $REGION

	CONTENT=$( cat config.json | jq \
		--arg artifact_bucket "$ARTIFACT_BUCKET" \
		'( .aws.s3.artifact_bucket |= $artifact_bucket )' )

	echo $CONTENT > config.json
fi

if [ -z $TABLE_NAME ]
then
	TABLE_NAME=todalytics-data-$ID
	aws dynamodb create-table \
		--table-name $TABLE_NAME \
		--attribute-definitions AttributeName=id,AttributeType=S \
		--key-schema AttributeName=id,KeyType=HASH \
		--billing-mode PAY_PER_REQUEST

	CONTENT=$( cat config.json | jq \
		--arg table_name "$TABLE_NAME" \
		'( .aws.dynamodb.table_name |= $table_name )' )

	echo $CONTENT > config.json
fi

CONFIG_JSON=$( cat config.json | jq )

API_TOKEN=$( jq -r  '.todoist.api_token' <<< "${CONFIG_JSON}" )
CLIENT_SECRET=$( jq -r  '.todoist.client_secret' <<< "${CONFIG_JSON}" )

aws s3 mv events.zip s3://$ARTIFACT_BUCKET/

aws cloudformation deploy \
	--template-file cft.yaml \
	--s3-bucket $ARTIFACT_BUCKET \
	--stack-name todalytics \
	--parameter-overrides \
		APIToken=$API_TOKEN \
		ClientSecret=$CLIENT_SECRET \
		ArtifactBucket=$ARTIFACT_BUCKET  \
		TableName=$TABLE_NAME \
	--capabilities CAPABILITY_NAMED_IAM \
	--no-fail-on-empty-changeset

echo 'launched stack resources'