#!/bin/bash

# start_api is for users to launch the application
# stack into their account using the release
# package from GitHub

if [[ $1 = "create_bucket" ]]; then
	ID=$(uuidgen)
	ID=${ID,,}

	ARTIFACT_BUCKET=todalytics-artifact-$ID

	REGION=$( aws configure get region )

	aws s3api create-bucket --bucket $ARTIFACT_BUCKET --region $REGION

	CONTENT=$( cat config.json | jq \
		--arg artifact_bucket "$ARTIFACT_BUCKET" \
		'( .aws.s3.artifact_bucket |= $artifact_bucket )' )

	echo $CONTENT > config.json
fi

CONFIG_JSON=$( cat config.json | jq )

ARTIFACT_BUCKET=$( jq -r  '.aws.s3.artifact_bucket' <<< "${CONFIG_JSON}" )

API_TOKEN=$( jq -r  '.todoist.api_token' <<< "${CONFIG_JSON}" )
CLIENT_SECRET=$( jq -r  '.todoist.client_secret' <<< "${CONFIG_JSON}" )

aws s3 mv update.zip s3://$ARTIFACT_BUCKET/

aws cloudformation deploy \
	--template-file cft.yaml \
	--s3-bucket $ARTIFACT_BUCKET \
	--stack-name todalytics \
	--parameter-overrides \
		APIToken=$API_TOKEN \
		ClientSecret=$CLIENT_SECRET \
		ArtifactBucket=$ARTIFACT_BUCKET  \
	--capabilities CAPABILITY_NAMED_IAM \
	--no-fail-on-empty-changeset

echo 'launched stack resources'